spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://beewoqf2yjm4hpvzsbxy-mysql.services.clever-cloud.com:3306/beewoqf2yjm4hpvzsbxy
    username: udzmibuhumbpcz5b
    password: yxWc7zA4jMGOBPT2Vosn
file:
  root:
    path: storage
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      accessTokenCookieName: accessToken
      refreshTokenCookieName: refreshToken
      expiration: ${JWT_EXP}
      refresh:
        expiration: ${JWT_REF_EXP}